asuka__blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ixtab/', admin.site.urls),
    path('card/', include('card_app.urls')),
    path('post/', include('post_app.urls')),
    path('summernote/', include('django_summernote.urls')),
]




urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

card_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'card_app'

urlpatterns = [
    path('', views.CardIndexView.as_view(), name='card_index'),
    path('recent/', views.CardTemplateView.as_view(), name='card_recent'),
    path('popular/', views.CardTemplateView.as_view(), name='card_popular'),
    path('post_tag/<str:tag>', views.CardPostTagView.as_view(), name='card_post_tag'),
    path('detail/<int:pk>', views.CardDetailView.as_view(), name='card_detail'),
    path('chemical_tag/<str:tag>/', views.CardChemicalTagView.as_view(), name='card_chemical_tag'),
    path('comment/<int:pk>/', views.CardCommentCreateView.as_view(), name='card_comment'),
    path('recomment/<int:pk>/<int:comment_pk>', views.CardReCommentCreateView.as_view(), name='card_recomment'),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post_app'

urlpatterns = [
    path('', views.PostIndexView.as_view(), name='post_index'),
    path('recent/', views.PostTemplateView.as_view(), name='post_recent'),
    path('popular/', views.PostTemplateView.as_view(), name='post_popular'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post_tag/<str:tag>/', views.PostTagView.as_view(), name='post_tag'),
    path('chemical_tag/<str:tag>/', views.PostChemicalTagView.as_view(), name='chemical_tag'),
    path('comment/<int:pk>/', views.PostCommentCreateView.as_view(), name='post_comment'),
    path('recomment/<int:pk>/<int:comment_pk>', views.PostReCommentCreateView.as_view(), name='post_recomment'),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

card_app/models.py
from django.db import models

class CardPostTag(models.Model):
    name = models.CharField(verbose_name='カード記事タグ', max_length=64)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'カード記事タグ'
        verbose_name_plural = 'カード記事タグ'


class CardChemicalTag(models.Model):
    name = models.CharField(verbose_name='カード化学タグ', max_length=256)        

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'カード化学タグ'
        verbose_name_plural = 'カード化学タグ'    


class Card(models.Model):
    title = models.CharField(verbose_name='タイトル', max_length=256)
    text = models.TextField(verbose_name='本文')
    post_tag = models.ManyToManyField(CardPostTag, verbose_name='記事カードタグ', blank=True)
    chemical_tag = models.ManyToManyField(CardChemicalTag, verbose_name='化学カードタグ', blank=True)
    created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    thumnail = models.ImageField(upload_to='card_thumnail/', blank=True, null=True)
    view_counter = models.IntegerField(verbose_name='閲覧数', default=0)
    friend_posts = models.ManyToManyField('self', verbose_name='関連記事', blank=True)
    detail = models.TextField(verbose_name='記事の説明', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'カード'
        verbose_name_plural = 'カード'    
        ordering = ('-created_at',)

class CardComment(models.Model):
    name = models.CharField(verbose_name='名前', max_length=256)
    text = models.TextField(verbose_name='コメント')
    thumnail = models.ImageField(upload_to='comment_thumnail/', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    target = models.ForeignKey(Card, on_delete=models.CASCADE, verbose_name='対象記事')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'カードコメント'
        verbose_name_plural = 'カードコメント'    
        ordering = ('-created_at',)
    


class CardReComment(models.Model):
    name = models.CharField(verbose_name='名前', max_length=256)
    text  = models.TextField(verbose_name='コメント')
    thumnail = models.ImageField(upload_to='recomment_thumnail/', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    target = models.ForeignKey(CardComment, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'カードコメントの返信'
        verbose_name_plural = 'カードコメントの返信'    
        ordering = ('-created_at',)
    

card_app/forms.py
from django import forms 
from .models import CardComment, CardReComment


class CardSearchForm(forms.Form):
    word = forms.CharField(label='ワード',required=False, widget=forms.TextInput(attrs={'placeholder':'キーワードを検索', 'class':'form-control'}))

    def clean_name(self):
        word = self.cleaned_data['word']
        return word

class CardCommentForm(forms.ModelForm):
    class Meta:
        model = CardComment
        fields = ('name', 'text', 'thumnail')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'thumnail': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }


class CardReCommentForm(forms.ModelForm):
    class Meta:
        model = CardReComment
        fields = ('name', 'text', 'thumnail')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'thumnail': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }

card_app/views.py
from django.shortcuts import render, redirect
from .models import Card, CardPostTag, CardChemicalTag, CardComment, CardReComment
from .forms import CardSearchForm, CardCommentForm, CardReCommentForm
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.db.models import Q
from post_app.models import Post


class CardBaseListView(ListView):
    paginate_by = 10
    model = Card

    def get_queryset(self):
        queryset = self.model.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['card_post_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        try:
            context['profile_img'] = Post.objects.get(id=1)
        except:
            context['profile_img'] = None
        return context

class CardIndexView(CardBaseListView):
    template_name = 'card_app/card_index.html'

    def get_queryset(self):
        try:
            word = self.request.GET['word']
        except:
            word = ''
        if word != '':
            queryset = self.model.objects.filter(Q(title__icontains=word) | Q(text__icontains=word))
        else:
            queryset = self.model.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context      


class CardTemplateView(CardIndexView):
    template_name = 'card_app/card_template.html'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context   


class CardPostTagView(CardBaseListView):
    template_name = 'card_app/card_list.html'
    def get_queryset(self):
        tag = self.kwargs['tag']
        queryset = self.model.objects.filter(post_tag__name=tag)
        return queryset

class CardChemicalTagView(CardBaseListView):
    template_neme = 'card_app/card_list.html'
    def get_queryset(self):
        tag = self.kwargs['tag']
        queryset = self.model.objects.filter(chemical_tag__name=tag)
        return queryset

class CardDetailView(DetailView):
    model = Card
    template_name = 'card_app/card_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs['pk']
        context['card'] = Card.objects.get(id=id)
        view_counter_add(context['card'])
        context = super().get_context_data(**kwargs)
        context['card_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        try:
            context['comment'] = context['card'].comment_set.all()
        except:
             context['comment'] = None
        try:
            context['recomment'] = context['comment'].recomment_set.all()
        except:
             context['recomment'] = None       
        context['recomment'] = CardReComment.objects.all()
        return context

class CardCommentCreateView(CreateView):
    model = CardComment
    template_name = 'card_app/comment.html'
    form_class = CardCommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.target = Card.objects.get(pk=post_pk)
        comment.save()
        return redirect('card_app:card_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['card_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        return context    

        
class CardReCommentCreateView(CreateView):
    model = CardReComment
    template_name = 'card_app/comment.html'
    form_class = CardReCommentForm
    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment_pk = self.kwargs['comment_pk']
        comment.target = CardComment.objects.get(pk=comment_pk)
        comment.save()
        return redirect('card_app:card_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['card_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        return context   




def view_counter_add(view_counter_class):
    view_counter_class.view_counter += 1
    view_counter_class.save()
    return view_counter_class

card_app/templates/card_app/base.html
{% load static %}
{% load cloudinary %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>asukaブログ</title>
    <style>
        html{
            background-color: gainsboro;
        }
    </style>
  </head>
  <body class="bg-transparent">


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block layout %}{% endblock %}
  </body>
</html>

card_app/templates/card_app/card_detail.html
{% extends 'card_app/layout.html' %}
{% block main %}
<article>
        <div class="card text-center mb-5">
                <p>作成日:{{card.created_at.date}}</p>
                <h2 class="text-muted mt-5">{{card.title}}</h2>
                <div class="card-body">
                        {% if card.thumnail %}
                        <img class="card-img-top img-fluid rounded " src="{{card.thumnail.url}}">
                        {% endif %}
                        {% if p.card_post_tag %}
                        <div class="conteiner">
                                <div class="row">
                                        {% for t in p.card_post_tag.all %}
                                        <p class="col">{{ t }}</p>
                                        {% endfor %}
                                </div>
                        </div>
                        {% endif %}
                        {% if p.card_chemical_tag %}
                        <div class="conteiner">
                                <div class="row">
                                        {% for t in p.card_chemical_tag.all %}
                                        <p class="col">{{ t }}</p>
                                        {% endfor %}
                                </div>
                        </div>
                        {% endif %}
                        <p>閲覧数 : {{card.view_counter}}</p>
                        <p>{{card.text|safe}}</p>
                </div>              
        </div>
</article>

{% if card.friend_posts.all %}
<div class="list-group mb-5">
        <h3>関連記事</h3>
        {% for r in card.friend_posts.all %}
        <a href="{% url 'card_app:card_detail' pk=r.id %}" class="mb-3 rounded list-group-item text-decoration-none">
                <div class="text-center">       
                        <h2>{{ r.title }}</h2>
                        {% if r.post_tag %}
                <div class="conteiner">
                        <div class="row">
                                {% for t in r.post_tag.all %}
                                <p class="col">{{ t }}</p>
                                {% endfor %}
                        </div>
                </div>
                {% endif %}
                {% if r.chemical_tag %}
                <div class="conteiner">
                        <div class="row">
                                {% for x in p.chemical_tag.all %}
                                <p class="col">{{ x }}</p>
                               {% endfor %}
                        </div>
                </div>
                {% endif %} 
                </div>
        </a>
        {% endfor %}

</div>
{% endif %}

<div class="text-center mb-5">
        <a href="{% url 'card_app:card_comment' pk=card.id %}" class=" btn btn-lg btn-primary">コメントする</a>
</div>

{% if comment %}
<div class=" container">
        <h2>コメント</h2>
        {% for c in comment %}
        <div class="card col my-3">
                <div class="py-2">
                        <h3 class="mb-3">{{c.name}}</h3>
                        {% if c.thumnail %}
                        <img class="card-img-top img-fluid rounded" src="{{c.thumnail.url}}">
                        {% endif %}
                        <p>{{c.text}}</p>
                        <p class="text-right">{{c.created_at}}</p>
                        <div class="text-right">
                                <a class="btn btn-primary" href="{% url 'card_app:card_recomment' pk=card.id comment_pk=c.pk %}">返信</a>
                        </div>
                        {% if c.recomment_set.all %}
                        <div class="container">
                                {% for r in c.recomment_set.all %}
                                <div class="card col my-3">
                                                <div class="pt-2">
                                                        <h3 class="mb-3">{{r.name}}</h3>
                                                        {% if r.thumnail %}
                                                        <img class="card-img-top rounded " src="{{r.thumnail.url}}">
                                                        {% endif %}
                                                        <p>{{r.text}}</p>
                                                        <p class="text-right">{{r.created_at}}</p>
                                                </div>
                                </div>
                                {% endfor %}
                        </div>
                        {% endif %}
                </div>
        </div>
        {% endfor %}
</div>
{% endif %}

{% endblock %}

card_app/templates/card_app/card_index.html
{% extends 'card_app/layout.html' %}
{% block main %}
<div></div>
<article>
        {% for p in card_list %}
        <div class="card text-center mb-5">
                <h3 class="text-muted mt-3">{{p.title}}</h3>
                <div class="card-body">
                        {% if p.thumnail %}
                        <img class="card-img-top img-fluid" src="{{p.thumnail.url}}"height="300">
                        {% endif %}
                        <p class="card-text">{{p.detail|safe}}</p>
                        {% if p.card_post_tag %}
                        <div class="conteiner">
                                <div class="row">
                                        {% for t in p.card_post_tag.all %}
                                        <p class="col">{{ t }}</p>
                                        {% endfor %}
                                </div>
                        </div>
                        {% endif %}
                        {% if p.card_chemical_tag %}
                        <div class="conteiner">
                                <div class="row">
                                        {% for t in p.card_chemical_tag.all %}
                                        <p class="col">{{ t }}</p>
                                        {% endfor %}
                                </div>
                        </div>
                        {% endif %}
                        <p>作成日:{{p.created_at.date}}</p>
                        <p>閲覧数 : {{p.view_counter}}</p>
                <a class="card-link btn btn-primary" href="{% url 'card_app:card_detail' pk=p.id %}">記事を見る</a>  
                </div>              
        </div>
        {% endfor %}
</article>

{% include 'card_app/includes/page.html' %}


{% endblock %}

card_app/templates/card_app/card_list.html
{% extends 'card_app/layout.html' %}
{% block main %}
<article>
    {% for p in card_list %}
    <div class="card text-center mb-5">
            <h3 class="text-muted mt-3">{{p.title}}</h3>
            <div class="card-body">
                    {% if p.thumnail %}
                    <img class="card-img-top img-fluid" src="{{p.thumnail.url}}">
                    {% endif %}
                    <p class="card-text">{{p.detail|safe}}</p>
                    {% if p.card_post_tag %}
                        <div class="conteiner">
                                <div class="row">
                                        {% for t in p.card_post_tag.all %}
                                        <p class="col">{{ t }}</p>
                                        {% endfor %}
                                </div>
                        </div>
                        {% endif %}
                        {% if p.card_chemical_tag %}
                        <div class="conteiner">
                                <div class="row">
                                        {% for t in p.card_chemical_tag.all %}
                                        <p class="col">{{ t }}</p>
                                        {% endfor %}
                                </div>
                        </div>
                        {% endif %}
                    <p>作成日:{{p.created_at.date}}</p>
                    <p>閲覧数 : {{p.view_counter}}</p>
            <a class="card-link btn btn-primary" href="{% url 'card_app:card_detail' pk=p.id %}">記事を見る</a>  
            </div>              
    </div>
    {% endfor %}
</article>

{% include 'card_app/includes/page.html' %}


{% endblock %}

card_app/templates/card_app/comment.html
{% extends 'card_app/layout.html' %}
{% block main %}
<form method="post">
        {% csrf_token %}
    {% for f in form %}
    <div class="form-group">
        <label>{{ f.label }}</label>
        {{f}}
    </div>
    {% endfor %}
    <button class="btn btn-primary" type="submit">コメントする</button>
</form>

{% endblock %}

card_app/templates/card_app/layout.html
{% extends 'card_app/base.html' %}

{% block layout %}

{% include 'card_app/includes/nav.html' %}

{% include 'card_app/includes/header.html' %}

<div class="container">
    <div class="row">
            <main class="col-12 col-md-8">
                {% block main %}{% endblock %}
            </main>
            <aside class="col-12 col-md-3 offset-md-1">
                <div class="item-group text-center mb-5 bg-white py-5 px-2 rounded">
                    {% if profile_img.thumnail.url %}
                    <img src="{{profile_img.thumnail.url}}" class="rounded-circle img-fluid">
                    {% endif %}
                    <h3>asuka</h3>
                    <p>都内理系大学の2年生19歳</p>
                    <p>大学では化学を専攻</p>
                    <p>プログラミング歴8ヶ月</p>
                    <p>Python Django</p>
                    <p>スクレイピング 機械学習</p>
                    <p>無機材料化学</p>
                    <a class="btn btn-primary" href="{% url 'post_app:post_detail' pk=1 %}">→→→詳しいプロフィール</a>
            </div>
            
            <div class="list-group mb-5">
                    <p class="list-group-item">post tag</p>
                    {% for t in card_post_tag %}
                    <a class="list-group-item text-decoration-none" href="{% url 'card_app:card_post_tag' tag=t.name %}">{{ t }}</a>
                    {% endfor %}
            </div>

            <div class="list-group mb-5">
                <p class="list-group-item">chemical tag</p>
                {% for t in card_chemical_tag %}
                <a class="list-group-item text-decoration-none" href="{% url 'card_app:card_chemical_tag' tag=t.name %}">{{ t }}</a>
                {% endfor %}
            </div>
            </aside>
    </div>
</div>

{% include 'card_app/includes/footer.html' %}

{% endblock %}