asuka__blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ixtab/', admin.site.urls),
    path('card/', include('card_app.urls')),
    path('post/', include('post_app.urls')),
    path('summernote/', include('django_summernote.urls')),
]




urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

card_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'card_app'

urlpatterns = [
    path('', views.CardIndexView.as_view(), name='card_index'),
    path('recent/', views.CardTemplateView.as_view(), name='card_recent'),
    path('popular/', views.CardTemplateView.as_view(), name='card_popular'),
    path('post_tag/<str:tag>', views.CardPostTagView.as_view(), name='card_post_tag'),
    path('detail/<int:pk>', views.CardDetailView.as_view(), name='card_detail'),
    path('chemical_tag/<str:tag>/', views.CardChemicalTagView.as_view(), name='card_chemical_tag'),
    path('comment/<int:pk>/', views.CardCommentCreateView.as_view(), name='card_comment'),
    path('recomment/<int:pk>/<int:comment_pk>', views.CardReCommentCreateView.as_view(), name='card_recomment'),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post_app'

urlpatterns = [
    path('', views.PostIndexView.as_view(), name='post_index'),
    path('recent/', views.PostTemplateView.as_view(), name='post_recent'),
    path('popular/', views.PostTemplateView.as_view(), name='post_popular'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post_tag/<str:tag>/', views.PostTagView.as_view(), name='post_tag'),
    path('chemical_tag/<str:tag>/', views.PostChemicalTagView.as_view(), name='chemical_tag'),
    path('comment/<int:pk>/', views.PostCommentCreateView.as_view(), name='post_comment'),
    path('recomment/<int:pk>/<int:comment_pk>', views.PostReCommentCreateView.as_view(), name='post_recomment'),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

card_app/models.py
from django.db import models

class CardPostTag(models.Model):
    name = models.CharField(verbose_name='カード記事タグ', max_length=64)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'カード記事タグ'
        verbose_name_plural = 'カード記事タグ'


class CardChemicalTag(models.Model):
    name = models.CharField(verbose_name='カード化学タグ', max_length=256)        

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'カード化学タグ'
        verbose_name_plural = 'カード化学タグ'    


class Card(models.Model):
    title = models.CharField(verbose_name='タイトル', max_length=256)
    text = models.TextField(verbose_name='本文')
    post_tag = models.ManyToManyField(CardPostTag, verbose_name='記事カードタグ', blank=True)
    chemical_tag = models.ManyToManyField(CardChemicalTag, verbose_name='化学カードタグ', blank=True)
    created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    thumnail = models.ImageField(upload_to='card_thumnail/', blank=True, null=True)
    view_counter = models.IntegerField(verbose_name='閲覧数', default=0)
    friend_posts = models.ManyToManyField('self', verbose_name='関連記事', blank=True)
    detail = models.TextField(verbose_name='記事の説明', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'カード'
        verbose_name_plural = 'カード'    
        ordering = ('-created_at',)

class CardComment(models.Model):
    name = models.CharField(verbose_name='名前', max_length=256)
    text = models.TextField(verbose_name='コメント')
    thumnail = models.ImageField(upload_to='comment_thumnail/', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    target = models.ForeignKey(Card, on_delete=models.CASCADE, verbose_name='対象記事')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'カードコメント'
        verbose_name_plural = 'カードコメント'    
        ordering = ('-created_at',)
    


class CardReComment(models.Model):
    name = models.CharField(verbose_name='名前', max_length=256)
    text  = models.TextField(verbose_name='コメント')
    thumnail = models.ImageField(upload_to='recomment_thumnail/', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    target = models.ForeignKey(CardComment, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'カードコメントの返信'
        verbose_name_plural = 'カードコメントの返信'    
        ordering = ('-created_at',)
    

card_app/forms.py
from django import forms 
from .models import CardComment, CardReComment


class CardSearchForm(forms.Form):
    word = forms.CharField(label='ワード',required=False, widget=forms.TextInput(attrs={'placeholder':'キーワードを検索', 'class':'form-control'}))

    def clean_name(self):
        word = self.cleaned_data['word']
        return word

class CardCommentForm(forms.ModelForm):
    class Meta:
        model = CardComment
        fields = ('name', 'text', 'thumnail')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'thumnail': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }


class CardReCommentForm(forms.ModelForm):
    class Meta:
        model = CardReComment
        fields = ('name', 'text', 'thumnail')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'thumnail': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }

card_app/views.py
from django.shortcuts import render, redirect
from .models import Card, CardPostTag, CardChemicalTag, CardComment, CardReComment
from .forms import CardSearchForm, CardCommentForm, CardReCommentForm
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.db.models import Q
from post_app.models import Post


class CardBaseListView(ListView):
    paginate_by = 10
    model = Card

    def get_queryset(self):
        queryset = self.model.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['card_post_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        try:
            context['profile_img'] = Post.objects.get(id=1)
        except:
            context['profile_img'] = None
        return context

class CardIndexView(CardBaseListView):
    template_name = 'card_app/card_index.html'

    def get_queryset(self):
        try:
            word = self.request.GET['word']
        except:
            word = ''
        if word != '':
            queryset = self.model.objects.filter(Q(title__icontains=word) | Q(text__icontains=word))
        else:
            queryset = self.model.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context      


class CardTemplateView(CardIndexView):
    template_name = 'card_app/card_template.html'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context   


class CardPostTagView(CardBaseListView):
    template_name = 'card_app/card_list.html'
    def get_queryset(self):
        tag = self.kwargs['tag']
        queryset = self.model.objects.filter(post_tag__name=tag)
        return queryset

class CardChemicalTagView(CardBaseListView):
    template_neme = 'card_app/card_list.html'
    def get_queryset(self):
        tag = self.kwargs['tag']
        queryset = self.model.objects.filter(chemical_tag__name=tag)
        return queryset

class CardDetailView(DetailView):
    model = Card
    template_name = 'card_app/card_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs['pk']
        context['card'] = Card.objects.get(id=id)
        view_counter_add(context['card'])
        context = super().get_context_data(**kwargs)
        context['card_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        try:
            context['comment'] = context['card'].comment_set.all()
        except:
             context['comment'] = None
        try:
            context['recomment'] = context['comment'].recomment_set.all()
        except:
             context['recomment'] = None       
        context['recomment'] = CardReComment.objects.all()
        return context

class CardCommentCreateView(CreateView):
    model = CardComment
    template_name = 'card_app/comment.html'
    form_class = CardCommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.target = Card.objects.get(pk=post_pk)
        comment.save()
        return redirect('card_app:card_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['card_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        return context    

        
class CardReCommentCreateView(CreateView):
    model = CardReComment
    template_name = 'card_app/comment.html'
    form_class = CardReCommentForm
    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment_pk = self.kwargs['comment_pk']
        comment.target = CardComment.objects.get(pk=comment_pk)
        comment.save()
        return redirect('card_app:card_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['card_tag'] = CardPostTag.objects.all()
        context['card_chemical_tag'] = CardChemicalTag.objects.all()
        context['card_search_form'] = CardSearchForm()
        return context   




def view_counter_add(view_counter_class):
    view_counter_class.view_counter += 1
    view_counter_class.save()
    return view_counter_class

card_app/templates/card_app/includes/footer.html
<footer class="text-center mt-5" style="height:100%; background: linear-gradient(-135deg,#f4ff61 ,#a8ff3e);">
        <div class="container">
            <h3>Thank you for watching!!</h3>
            <h3>見てくれてありがとう！！</h3>
        </div>
    </footer>

card_app/templates/card_app/includes/header.html
<header class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>asukaブログ</h1>
        <hr class="my-4">
        <p class="h5">現在理系大学2年生のasukaです。Python、Django、Bootstrap、HTML、CSS、スクレイピング、機械学習を主に扱っています。</p>
        <p class="h5">大学では化学を専攻しているので、化学についても投稿していきたいと思います。</p>
        <p class="h5">このブログや記事について共有してもらえるとありがたいです。</p>
        <p class="h5">よろしくおねがいします！</p>
    </div>
</header>

card_app/templates/card_app/includes/nav.html
<nav class="navbar navbar-light" style="background: linear-gradient(-135deg,#f4ff61 ,#a8ff3e);">
    <button class="btn btn-primary navbar-toggler" 
    data-toggle="collapse"
    data-target="#example-1"
    aria-expand="false"
    aria-controls="example-1"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="example-1">
  <div class="container" style="margin-top:10px;">
      <div class="row text-center">
          <div class="col-lg-3 h3"><div class="card"><a class="text-decoration-none" href="{% url 'card_app:card_index' %}">home</a></div></div>
          <div class="col-lg-3 h3"><div class="card"><a class="text-decoration-none" href="{% url 'post_app:post_index'  %}">post</a></div></div>
          <div class="col-lg-3 h3"><div class="card"><a class="text-decoration-none" href="https://twitter.com/asuka__blog" target="_blank">@asuka__blog</a></div></div>
          <div class="col-lg-3 h3"><div class="card form-group">
              <form class="" action="{% url 'card_app:card_index' %}">
                  {{ card_search_form.word }}
                  <button class="btn mb-2 btn-block" type="submit">検索</button>                
              </form>
            </div>    
          </div>
      </div>
  </div>
  </div>
</nav>

card_app/templates/card_app/includes/page.html
<ul class="pagination justify-content-center">
    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}

    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
</ul>